package: url
version: '2.2.1'
author: Alexander Walther, urspr. Thomas Blum
supportpage: 'https://github.com/alexplusde/url/'

page:
    title: 'translate:url'
    perm: admin[]
    pjax: false
    icon: rex-icon fa fa-anchor
    subpages:
        generator:
            title: 'translate:generator'
            subpages:
                profiles:
                    title: 'translate:url_generator_profiles'
                urls:
                    title: 'translate:url_generator_urls_generated'
        help:
            title: translate:url_generator_help
            pjax: false
            subPath: README.md
            itemClass: pull-right

requires:
    redaxo: ^5.18.0
    packages:
        yrewrite: ^2.10.0
    php:
        extensions: [intl]
        version: '>=8.2'
